result/models.py
from datetime import datetime
import enum
import ast
import os
import os.path as op

from sqlalchemy import Column, Integer, String, DateTime, Enum

from app import db, PLOT_CACHES_FOLDER

class ResultStatus(enum.Enum):
    pending = "PENDING"
    processing = "PROCESSING"
    complete = "COMPLETE"
    failed = "FAILED"

class Result(db.Model):
    id = Column(Integer, primary_key=True)
    status = Column(Enum(ResultStatus), default=ResultStatus.pending.name)
    creation_date = Column(DateTime, default=datetime.now)
    file = Column(String)
    exception = Column(String)
    analysis_parameters = Column(String, default="{}")
    calculated_values = Column(String, default="[]")
    detector_start_time = Column(DateTime)
    detector_end_time = Column(DateTime)

    def get_plot(self, plot_name):
        if op.exists(op.join(self.cache_folder, plot_name + ".html")):
            with open(op.join(self.cache_folder, plot_name + ".html"), "r") as cache_file:
                return cache_file.read()
        return None

    def save_plot(self, plot_name, contents):
        if not op.exists(self.cache_folder):
            os.makedirs(self.cache_folder)
        with open(op.join(self.cache_folder, plot_name + ".html"), "w") as cache_file:
            cache_file.write(contents)

    def clear_plots(self):
        if os.path.exists(self.cache_folder):
            for filename in os.listdir(self.cache_folder):
                os.unlink(op.join(self.cache_folder, filename))
        self.calculated_values = "[]"

    @property
    def cache_folder(self):
        return op.join(PLOT_CACHES_FOLDER, str(self.id))

    @property
    def parameters(self):
        return ast.literal_eval(self.analysis_parameters)

    @parameters.setter
    def parameters(self, p):
        self.analysis_parameters = str(p)

    @property
    def filename(self):
        return op.basename(self.file)

    @property
    def file_exists(self):
        return op.exists(self.file)

    @property
    def filesize(self):
        return os.path.getsize(self.file)

    @property
    def failed(self):
        return self.status == ResultStatus.failed

    @property
    def complete(self):
        return self.status == ResultStatus.complete

    @property
    def in_progress(self):
        return self.status in (ResultStatus.pending, ResultStatus.processing)

    @property
    def label_type(self):
        return {ResultStatus.pending:"info",
                ResultStatus.processing:"warning",
                ResultStatus.complete:"success",
                ResultStatus.failed:"danger",}[self.status]

    @property
    def simple_creation_date(self):
        return self.creation_date.strftime("%Y-%m-%d %H:%M:%S")

    @property
    def detector_run_time_hms(self):
        dt = self.detector_end_time - self.detector_start_time
        seconds = dt.seconds
        minutes, seconds = divmod(seconds, 60)
        hours, minutes = divmod(minutes, 60)
        return "{}h {}m {}s".format(hours, minutes, seconds)

    def add_calculated_value(self, for_plot, name, value):
        calc = ast.literal_eval(self.calculated_values)
        calc.append((for_plot, name, value))
        self.calculated_values = str(calc)


    def calculated_values_for_plot(self, for_plot):
        calc = ast.literal_eval(self.calculated_values)
        for plot, name, value in calc:
            if plot == for_plot:
                yield name, value

result/views.py
from flask import Blueprint, render_template, flash, request, jsonify, send_from_directory, redirect, url_for
from werkzeug.utils import secure_filename

import random
import time
import os
import os.path as op
from collections import OrderedDict
from operator import itemgetter
import inspect
import json
from datetime import datetime

import plotly
import plotly.graph_objs as go

from detector.detector import Path, path_passes_through_cube

from result.models import Result, ResultStatus
from analysis.analysis import Analysis

from app import RESULTS_FOLDER, db

result = Blueprint("result", __name__)

@result.route("/upload_result", methods=["GET", "POST"])
def upload_result():
    """
    Route to upload result file to database
    POST with requests.post("http://127.0.0.1:5000/upload_result", files={"field_name":open("path/to/file", "r")})
    :return: HTTP response
    """
    if len(request.files) == 0:
        return jsonify(success=False), 400

    file = next(request.files.values())
    filename = secure_filename(file.filename)
    file.save(op.join(RESULTS_FOLDER, filename))

    result = Result()
    result.file = op.join(RESULTS_FOLDER, filename)

    result.detector_start_time = datetime.fromtimestamp(float(request.form["detector_start_time"]))
    result.detector_end_time = datetime.fromtimestamp(float(request.form["detector_end_time"]))

    db.session.add(result)
    db.session.commit()

    return jsonify(success=True, result_id=result.id), 200

@result.route("/results")
def result_list():
    results = Result.query.all()[::-1]
    return render_template("result_list.html", results=results)

@result.route("/result/<int:result_id>")
def result_page(result_id):
    """
    todo: comment on individual results
    """
    result = Result.query.get(result_id)

    parameters = result.parameters
    argspec = inspect.getfullargspec(Analysis.active_analysis.analyse)
    kwargs = dict(zip(argspec.args[-len(argspec.defaults):], argspec.defaults))
    for name, value in kwargs.items():
        if name not in parameters:
            parameters[name] = value

    # Remove old parameters
    for name in list(parameters.keys()):
        if name not in kwargs:
            del parameters[name]

    parameters = OrderedDict(sorted(parameters.items(), key=itemgetter(0)))

    def parameter_type(parameter):
        if type(parameters[parameter]) is bool:
            return "checkbox"
        return "text"


    plots = []
    plot_priority = ["pulses_histogram", "path_track", "density_slice", "density_dist"]
    if not result.failed:
        for plot_name in plot_priority:
            plot = result.get_plot(plot_name)
            if not plot is None:
                plots.append((plot_name, plot))

    return render_template("result.html", result=result, plots=plots, parameters=parameters, parameter_type=parameter_type)

@result.route("/jump_to_result", methods=["GET", "POST"])
def jump_to_result():
    result_id = request.form["jump_to_id"]
    if not result_id.isdigit():
        flash("Could not find result with that ID", "error")
        return redirect(url_for("result.result_list"))
    result = Result.query.get(result_id)
    if result is None:
        flash("Could not find result with that ID", "error")
        return redirect(url_for("result.result_list"))
    return redirect(url_for("result.result_page", result_id=result.id))

@result.route("/reanalyse/<int:result_id>", methods=["GET", "POST"])
def reanalyse(result_id):
    result = Result.query.get(result_id)
    result.clear_plots()
    argspec = inspect.getfullargspec(Analysis.active_analysis.analyse)
    kwargs = dict(zip(argspec.args[-len(argspec.defaults):], argspec.defaults))
    parameters = result.parameters
    for name, value in request.form.items():
        if len(value) > 0:
            if name in kwargs:
                parameters[name] = type(kwargs[name])(value)


    result.parameters = parameters
    result.status = ResultStatus.pending
    db.session.commit()
    return redirect(url_for("result.result_page", result_id=result_id))

@result.route("/download_data_file/<int:result_id>")
def download_data_file(result_id):
    # for name in dir(request):
    #     if not name.startswith("__"):
    #         print(name, getattr(request, name))
    result = Result.query.get(result_id)
    if result is None:
        flash("Result {} does not exist".format(result_id), "error")
        return redirect(request.referrer)
    if not op.exists(result.file):
        flash("Data file ({}) no longer exists on the server".format(result.file), "error")
        return redirect(request.referrer)
    return send_from_directory(directory=RESULTS_FOLDER, filename=result.filename, attachment_filename="result-{}-datafile.txt".format(result_id), as_attachment=True)

@result.route("/check_progress/<int:result_id>")
def check_progress(result_id):
    state = request.args.get("current_status", "complete")
    result = Result.query.get(result_id)
    reload = result.status.name != state
    return jsonify(dict(reload=reload))


@result.route("/result_example")
def example_result():
    """
    idea: cache plotly html files, offer "replot" on result page
    idea: when path start/end are quantized, cache volume check results
    todo: move analysis code out of view
    """

    start_time = time.perf_counter()
    #p = Path(0.55, 0.55, 1, 0.55, 0.55, 0)
    #print(path_passes_through_cube(p, 0.6, 0.6, 0.6, 0.1, 0.1, 0.1))

    lines = []
    #xs = []
    #ys = []
    #zs = []
    st = time.time()
    # 10000 Request time: 69.24448532398439 with obstruction
    # 10000 Request time: 70.08756806654017 without obstruction
    # 10000 Request time: 7.622724069724689 with easy checks
    # 100000 Request time: 729.9082427835476 without caching
    # 100000 Request time: 754.6030013966841 with caching
    # 100000 Request time: 76.17804744634259 with easy checks
    while len(lines) < 800000:
        # xi, yi, zi = random.random(), random.random(), 1
        # xf, yf, zf = xi+(random.random()-0.5), yi+(random.random()-0.5), 0
        xi, yi, zi = round(0.05 + 0.1*random.randint(0, 9), 2), round(0.05 + 0.1*random.randint(0, 9), 2), 1
        #xf, yf, zf = 0.02 + 0.04*random.randint(0, 24), 0.02 + 0.04*random.randint(0, 24), 0
        #xi, yi, zi = random.random(), random.random(), 1
        #xf, yf, zf = xi+(random.random()-0.5)/2, yi+(random.random()-0.5)/2, 0
        xf, yf, zf = round(xi+(0.1*random.randint(0, 6)-0.3), 2), round(yi+(0.1*random.randint(0, 6)-0.3), 2), 0
        if (0 < xf < 1) and (0 < yf < 1):
            p = Path(xi, yi, zi, xf, yf, zf)
            if path_passes_through_cube(p, 0.30, 0.40, 0.0, 0.2, 0.2, 0.2) and random.random() > 0.2:
                continue
            if path_passes_through_cube(p, 0.50, 0.40, 0.0, 0.2, 0.2, 0.2) and random.random() > 0.6:
                continue
            lines.append(([xi, xf], [yi, yf], [zi, zf]))
            #xs += [xi, xf, None]
            #ys += [yi, yf, None]
            #zs += [zi, zf, None]
            #lines.append(None)

    print("Random generation time: {}".format(time.time()-st))

    datas = []
    col = '#1f77b4'
    xs = []
    ys = []
    zs = []
    paths_shown = 0
    for line in lines:
        if random.random() > (400/len(lines)):
            continue
        xs += line[0] + [None,]
        ys += line[1] + [None,]
        zs += line[2] + [None,]
        paths_shown += 1
    datas.append(
        go.Scatter3d(x=xs, y=ys, z=zs,
                        hoverinfo="none",
                        connectgaps=False,
                        marker=dict(
                            size=4,
                            color=zs,
                            colorscale='Viridis',
                        ),
                        line=dict(
                            color=col,
                            width=1
                        ),
                     )
    )



    """for line in lines:
        if random.random() > (200/len(lines)):
            continue
        col = '#1f77b4'
        p = Path(line[0][0], line[1][0], line[2][0], line[0][1], line[1][1], line[2][1])
        if path_passes_through_cube(p, 0.5, 0.5, 0.5, 0.1, 0.1, 0.1):
            col = "#ff0000"
        datas.append(go.Scatter3d(
            x=line[0], y=line[1], z=line[2],
            marker=dict(
                size=4,
                color=line[2],
                colorscale='Viridis',
            ),
            line=dict(
                color=col,
                width=1
            ),
            hoverinfo="none",
        ))"""

    x = [(0.4, 0.6), (0.6, 0.6), (0.6, 0.4), (0.4, 0.4), (0.4, 0.6), (0.6, 0.6), (0.6, 0.4), (0.4, 0.4), (0.4, 0.4), (0.6, 0.6), (0.4, 0.4), (0.6, 0.6)]
    y = [(0.4, 0.4), (0.4, 0.4), (0.4, 0.4), (0.4, 0.4), (0.6, 0.6), (0.6, 0.6), (0.6, 0.6), (0.6, 0.6), (0.4, 0.6), (0.4, 0.6), (0.4, 0.6), (0.4, 0.6)]
    z = [(0.4, 0.4), (0.4, 0.6), (0.6, 0.6), (0.6, 0.4), (0.4, 0.4), (0.4, 0.6), (0.6, 0.6), (0.6, 0.4), (0.4, 0.4), (0.4, 0.4), (0.6, 0.6), (0.6, 0.6)]

    for i in range(0, len(x)):
        datas.append(go.Scatter3d(
            x=x[i], y=y[i], z=z[i],
            marker=dict(
                size=2,
                color="#0000ff",
            ),
            line=dict(
                color="#0000ff",
                width=1
            ),
            hoverinfo="none",
        ))

    layout = dict(
        width=700,
        height=700,
        autosize=False,
        title='muon paths',
        showlegend = False,
        scene=dict(
            xaxis=dict(
                gridcolor='rgb(255, 255, 255)',
                zerolinecolor='rgb(255, 255, 255)',
                showbackground=True,
                backgroundcolor='rgb(230, 230,230)',
                range=[0, 1],
            ),
            yaxis=dict(
                gridcolor='rgb(255, 255, 255)',
                zerolinecolor='rgb(255, 255, 255)',
                showbackground=True,

templates/detector_status.html
{% extends "master.html" %}
{% block title %}Detector status{% endblock %}
{% block head %}
    <script type=text/javascript src="{{ url_for('static', filename='js/jquery-3.1.1.min.js') }}"></script>
    <script type=text/javascript>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/detector_status.js') }}"></script>
{% endblock %}
{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Detector Status</h2>
        </div>
        <div class="panel-body">
            <p>Status: {{ status }}</p>
            {% if detector_running %}
                <script>run_scripts = true;</script>
                <p id="run_timer">Run time</p>
                <p id="current_muons">Current light pulses: </p>
                <script>detector_running_seconds = {{ current_seconds }}</script>
                <script>countTimer();</script>
            {% endif %}
            <form method="post" action="{{ url_for("detector.detector_status") }}">
                {% if not detector_running %}
                    <button type="submit" class="btn btn-primary" name="submit" value="start">Start</button>
                {% else %}
                    <button type="submit" class="btn btn-danger" name="submit" value="stop">Stop</button>
                {% endif %}
            </form>
        </div>
    </div>
{% endblock %}

templates/example_result.html
{% extends "master.html" %}
{% block title %}Example result{% endblock %}
{% block body %}
    <p>Total events: {{ total_events }}</p>
    <p>Paths shown: {{ paths_shown }}</p>
    <p>Request time: {{ request_time|round(2) }}s</p>
    {{ charthtml|safe }}
    {{ chartdensity|safe }}
    {{ intersect_distribution|safe }}
{% endblock %}

templates/generic.html
{% extends "master.html" %}
{% block title %}{{ title }}{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">{{ panel_title }}</h2>
        </div>
        <div class="panel-body">
            {{ body|safe }}
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends "master.html" %}
{% block title %}Index{% endblock %}

{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Index</h2>
        </div>
        <div class="panel-body">
            Hello, world.
        </div>
    </div>
{% endblock %}

templates/master.html
{% import 'admin/layout.html' as layout with context -%}
{% import 'admin/static.html' as admin_static with context %}
<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
<link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
<script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block head %}{% endblock %}
</head>
<body>
    <div class="container">
    {{ nav.nav_bar_renderer.render() }}
    <div style="padding-top: 60px;">
        {{ layout.messages() }}
        {% block body %}{% endblock %}
    </div>
</div>
</body>
</html>

templates/result.html
{% extends "master.html" %}
{% block title %}Result {{ result.id }}{% endblock %}
{% block head %}
    <script type=text/javascript src="{{ url_for('static', filename='js/jquery-3.1.1.min.js') }}"></script>
    <script type=text/javascript>
        $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
    </script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/result.js') }}"></script>
    <script>run_scripts = {{ result.in_progress|tojson }};</script>
    <script>current_status = {{ result.status.name|tojson }};</script>
    <script>result_id = {{ result.id|tojson }};</script>
{% endblock %}
{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Result: {{ result.id }}</h2>
        </div>
        <ul class="list-group">
            <li class="list-group-item"><b>Status: </b><span class="label label-{{ result.label_type }}">{{ result.status.value }}</span></li>
            <li class="list-group-item"><b>Data file: </b>{{ result.file }}
                {% if result.file_exists %}
                    <a href="{{ url_for("result.download_data_file", result_id=result.id) }}">
                        <span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span>
                    </a>
                {% endif %}
            </li>
            {% if result.file_exists %}
                <li class="list-group-item"><b>Data file size: </b>{{ (result.filesize/1024)|round(2) }} kb</li>
            {% else %}
                <li class="list-group-item"><b>Data file no longer exists</b></li>
            {% endif %}
            <li class="list-group-item"><b>Detector run duration: </b>{{ result.detector_run_time_hms }}</li>
            <li class="list-group-item"><b>Database entry creation date: </b>{{ result.creation_date }}</li>

        </ul>
    </div>

    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Analysis parameters</h2>
        </div>
        <div class="panel-body">
            <form class="form-horizontal" action="{{ url_for("result.reanalyse", result_id=result.id) }}" method="POST">
                {% for name, value in parameters.items() %}
                    <div class="form-group">
                        <label class="control-label col-sm-2" for="{{ name }}">{{ name }}</label>
                        <div class="col-sm-3">
                            {% if parameter_type(name) == "checkbox" %}
                                <input type="{{ parameter_type(name) }}" class="custom-control-input" id="{{ name }}" name="{{ name }}" style="height: 27px;" {% if value %}checked{% endif %} {%if result.in_progress %}disabled{% endif %}>
                            {% else %}
                                <input type="{{ parameter_type(name) }}" class="form-control" id="{{ name }}" name="{{ name }}" placeholder="{{ value }}" {%if result.in_progress %}disabled{% endif %}>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
                {% if result.complete or result.failed %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                          <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-repeat"></span> Reanalyse</button>
                        </div>
                    </div>
                {% endif %}
            </form>
        </div>
    </div>

    {% if result.failed %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Error</h2>
            </div>
            <div class="panel-body">
                <pre style="color: red;">{{ result.exception }}</pre>
            </div>
        </div>
    {% endif %}
    {% if result.complete %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h2 class="panel-title">Plots</h2>
            </div>
            <div class="panel-body">
                {% for plot_name, plot in plots %}
                    {{ plot|safe }}
                    {% for (name, value) in result.calculated_values_for_plot(plot_name) %}
                        <p>{{ name }} = {{ value }}</p>
                    {% endfor %}
                {% endfor %}
            </div>
        </div>
    {% endif %}
{% endblock %}

templates/result_list.html
{% extends "master.html" %}
{% block title %}Results{% endblock %}


{% block body %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h2 class="panel-title">Results</h2>
        </div>
        <div class="panel-body">
            <form action="{{ url_for('result.jump_to_result') }}" method="POST">
                <div class="row">
                    <div class="col-lg-3">
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="Jump to result..." id="jump_to_id" name="jump_to_id">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">Go</button>
                            </span>
                        </div>
                    </div>
                </div>
            </form>
        </div>
        <table class="table table-striped">
            <thead>
            <tr>
                <th style="font-weight: normal;">Result ID</th>
                <th style="font-weight: normal;">Status</th>
                <th style="font-weight: normal;">Run duration</th>
                <th style="font-weight: normal;">File</th>
            </tr>
            </thead>
            <tbody>
            {% for result in results %}
                <tr>
                    <td><a href="{{ url_for('result.result_page', result_id=result.id) }}">Result {{ result.id }}</a></td>
                    <td><span class="label label-{{ result.label_type }}">{{ result.status.value }}</span></td>
                    <td>{{ result.detector_run_time_hms }}</td>
                    <td>
                        {{ result.file }}
                        <a href="{{ url_for("result.download_data_file", result_id=result.id) }}">
                            <span class="glyphicon glyphicon-cloud-download" aria-hidden="true"></span>
                        </a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}